substitutions:
  devicename: esphome-wmbus-heltec-v3
  friendly_name: "wMBus Bridge Heltec V3"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  min_version: 2026.1.3

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  cpu_frequency: 160MHz
  framework:
    type: esp-idf

external_components:
  - source: github://Kustonium/esphome-wmbus-bridge-rawonly@main
    components: [wmbus_radio]
    refresh: 0s

logger:
  level: info
  logs:
    mqtt: warn
    component: warn

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

api:
ota:
  - platform: esphome

switch:
  - platform: gpio
    id: vext
    pin: GPIO36
    internal: true
    inverted: true
    restore_mode: ALWAYS_ON

spi:
  clk_pin: GPIO9
  mosi_pin: GPIO10
  miso_pin: GPIO11

wmbus_radio:
  radio_type: SX1262
  cs_pin: GPIO8
  reset_pin: GPIO12
  busy_pin: GPIO13
  irq_pin:
    number: GPIO14
    mode: input
  has_tcxo: true
  dio2_rf_switch: false
  rx_gain: boosted
  long_gfsk_packets: true
  listen_mode: t1
  listen_mode_filter_after_parse: false
  diagnostic_mode: normal
