substitutions:
  devicename: esphome-wmbus-cc1101
  friendly_name: "wMBus Bridge CC1101"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  min_version: 2026.1.3
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

external_components:
  - source: github://Kustonium/esphome-wmbus-bridge-rawonly@main
    components: [wmbus_radio]
    refresh: 0s

logger:
  level: info
  logs:
    mqtt: warn
    component: warn

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

api:
ota:
  - platform: esphome
mdns:
  disabled: false
time:
  - platform: homeassistant

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO6
  miso_pin: GPIO7

wmbus_radio:
  radio_type: CC1101
  cc1101_allow_experimental: true

  frequency: 868.950
  cs_pin: GPIO4

  gdo0_pin:
    number: GPIO3
    mode: input

  gdo2_pin:
    number: GPIO2
    mode: input

  listen_mode: t1
  listen_mode_filter_after_parse: false

  topic_name: "cc1101"
  diagnostic_mode: normal
  diagnostic_summary_interval: 60s
